Feature/997 Perform a staged migration of Stages & Statuses data
jac-uk/digital-platform pull request #1019
Opened 2024-02-20 16:31 UTC by HalcyonJAC

2024-02-23 10:28 UTC, warrensearle commented
@HalcyonJAC how much effort would it be write a migration script to go back the other way - from v2 stages and statuses back to v1 stages and statuses?

2024-02-26 09:54 UTC, warrensearle commented
As discussed this morning @HalcyonJAC please can you create a cloud function wrapper for the migration script, and also enable roll-back of the changes (store the original statuses in the `applicationRecord` document).

This will then be called on a per-exercise basis from the admin UI.

2024-02-29 16:00 UTC, warrensearle requested changes
This looks great @HalcyonJAC. Your code is always really nicely written and easy to follow.

We do need to update the stages. I'll send across proposal mappings for those asap

👍

2024-02-29 16:00 UTC, warrensearle commented on functions/actions/applicationRecords/updateApplicationRecordStageStatus.js
> +    const applicationRecords = await getDocuments(db.collection('applicationRecords').where('exercise.id', '==', exerciseId));
We could speed this up slightly, particularly when run via nodescript, by adding `.select('_backup', 'stage', 'status')` to the query. So the line becomes something like:
```
    const applicationRecords = await getDocuments(db.collection('applicationRecords').where('exercise.id', '==', exerciseId).select('_backup', 'stage', 'status'));
```

2024-03-04 10:06 UTC, HalcyonJAC commented on functions/actions/applicationRecords/updateApplicationRecordStageStatus.js
> +    const applicationRecords = await getDocuments(db.collection('applicationRecords').where('exercise.id', '==', exerciseId));
Thank you for the suggestion 👍

2024-03-12 09:55 UTC, drieJAC approved these changes

2024-03-12 22:33 UTC, warrensearle approved these changes
Great to see some unit tests in there 😃

2024-03-12 22:34 UTC, merged