create checksums
jac-uk/digital-platform pull request #1138
Opened 2024-07-10 16:44 UTC by tomlovesgithub

Create a new collection in the firestore db to store checksums with the following fields: filepath, filename, checksum, created_at

Write a function which creates a checksum from a file

Create a checksum when a file passes the virus check and store it in the new collection

- pending tests

2024-08-27 10:28 UTC, KoWeiJAC approved these changes

2024-08-27 10:28 UTC, KoWeiJAC commented on functions/actions/malware-scanning/scanFile.js
> +        return { error: e.message };
Shall we log the e.message of scan API for troubleshooting ?

2024-08-30 09:00 UTC, warrensearle requested changes

2024-09-12 15:17 UTC, tomlovesgithub commented on functions/actions/malware-scanning/addChecksumToFirestore.js
> +    const docRef = checksumsCollection.doc(fileName); // Use the file name as the document ID
Good point! but files are stored within sub-collections so we shoudn't have this issue hopefully!

2024-09-12 16:28 UTC, warrensearle approved these changes

2024-09-13 09:32 UTC, drieJAC approved these changes

2024-09-13 10:23 UTC, HalcyonJAC commented on functions/actions/malware-scanning/scanFileAndCreateChecksum.js
> +import { addChecksumToFirestore } from './addChecksumToFirestore.js';
We might need to pass parameters when importing the function like:
```js
import addChecksumToFirestoreInit from './addChecksumToFirestore.js';
const { addChecksumToFirestore } = addChecksumToFirestoreInit(firebase, db);
```

2024-09-13 10:30 UTC, HalcyonJAC commented on functions/scheduledFunctions/runScannerTest.js
> +const runScannerTest = runScannerTestFile(config, firebase);
We might need to change it to below as `runScannerTest.js` is exported as default and three parameters are required:

```js
import runScannerTestFile from '../actions/malware-scanning/runScannerTest.js';
const runScannerTest = runScannerTestFile(config, firebase, db);
```

2024-09-13 14:05 UTC, HalcyonJAC commented on functions/scheduledFunctions/runScannerTest.js
> +const runScannerTest = runScannerTestInit(config, firebase);
The `db` object needs to be passed into the function.

2024-09-13 14:17 UTC, HalcyonJAC approved these changes
👍

2024-09-17 09:33 UTC, merged