Bugfix/Fix NPM Vulnerabilities
jac-uk/digital-platform pull request #1160
Opened 2024-08-01 10:41 UTC by HalcyonJAC

2024-08-02 22:51 UTC, warrensearle reviewed
Are you sure this is correct? Seems strange to go back to allowing version 0.0.1 and above when previously it was version 4.2.6 and above!

2024-08-05 10:54 UTC, tomlovesgithub requested changes
Can we discuss this change at the next dev meeting? seems a little sketchy to downgrade to such an early version

2024-08-15 14:39 UTC, tomlovesgithub approved these changes

2024-08-15 20:46 UTC, warrensearle approved these changes

2024-08-16 07:57 UTC, merged