Change rules for LOGS and changing the assessor
jac-uk/digital-platform pull request #454
Opened 2020-11-17 01:01 UTC by lloback

This PR changes permissions for two tasks that I was working on:

LOGS
Change ASSESSORS

2020-11-17 23:50 UTC, warrensearle requested changes

2020-11-17 23:50 UTC, warrensearle commented on database/firestore.rules
> +      allow get, read, create, write, update: if userIsAuthenticated();
There are un-necessary verbs here:
`read` and `write` are high-level and cover the relevant lower level verbs
`read` implies `list` and `get`
`write` implies `create`, `update`, `delete`

2020-11-17 23:50 UTC, warrensearle commented on database/firestore.rules
> +      // allow candidates update their own logs
This doesn't restrict candidate to only updating their own log

2020-11-18 10:51 UTC, lloback commented
The only thing that seems to works here is:

```
match /logs/{document=**} {
      // allow candidates update their own logs
      allow read, write: if userIsAuthenticated();
      allow read: if userIsAuthenticated() && userIsJAC();
    }
```

2020-11-18 10:53 UTC, lloback commented
I've tried different combinatiosn and it doesn't work:

```
match /logs/login/{id} {
      allow read, write: if userIsAuthenticated() && currentUser() == id; // DON"T WORK
      allow read: if userIsAuthenticated() && userIsJAC();
    }
```

```
match /logs/{document=**}/{id} {
      allow read, write: if userIsAuthenticated() && currentUser() == id; // DON"T WORK
      allow read: if userIsAuthenticated() && userIsJAC();
    }
```

2020-11-18 11:45 UTC, warrensearle commented
I think the following should do the trick:
```
match /logs/login/{id}/{logId} {
      // allow candidates update their own logs
      allow read, write: if userIsAuthenticated() && currentUser() == id;
      allow read: if userIsAuthenticated() && userIsJAC();
    }
```

2020-11-18 12:19 UTC, lloback commented on database/firestore.rules
> +      allow get, read, create, write, update: if userIsAuthenticated();
this is implemented.

2020-11-18 12:21 UTC, warrensearle approved these changes
👍

2020-11-18 12:21 UTC, merged