Feature/admin 1312 notifications
jac-uk/digital-platform pull request #570
Opened 2021-05-28 16:48 UTC by mbrookeswebdev

@warrensearle please see the [description of workflow in Admin branch of this epic](https://github.com/jac-uk/admin/compare/feature/1327-enable-request-of-character-check-form-completion)

2021-06-22 07:32 UTC, lloback commented
@mbrookeswebdev let us know when this is ready for review.

2021-07-13 08:12 UTC, mbrookeswebdev commented
This work needs to be integrated with Staged Application feature after I've finished preparation for access to JO API.

2021-07-19 13:52 UTC, mbrookeswebdev commented
Ready to code review (please do it together with #[1327](https://github.com/jac-uk/admin/pull/1357) and #[773](https://github.com/jac-uk/apply/pull/791)).

2021-07-20 12:35 UTC, warrensearle requested changes

2021-07-20 12:35 UTC, warrensearle commented on functions/callableFunctions/updateCharacterChecksStatus.js
> +});
Looking at related work here https://github.com/jac-uk/apply/pull/791 I think this might be better as a background function rather than callable function. DM me and we can discuss further.

2021-07-21 13:06 UTC, mbrookeswebdev commented on functions/callableFunctions/updateCharacterChecksStatus.js
> +});
@warrensearle Thanks Warren, I'll have a look at #791 and make changes as requested.

2021-07-25 16:07 UTC, mbrookeswebdev commented on functions/callableFunctions/updateCharacterChecksStatus.js
> +});
Done

2021-07-26 09:21 UTC, warrensearle requested changes
Looks good, just one small tweak 😄

2021-07-26 09:21 UTC, warrensearle commented on functions/actions/applications/onUpdate.js
> +    }
We should check existence of `.characterChecks` before looking at `.characterChecks.status` as not all applications will have the `characterChecks` field

2021-07-26 12:51 UTC, mbrookeswebdev commented on functions/actions/applications/onUpdate.js
> +    }
I've added checks

2021-07-27 08:45 UTC, warrensearle approved these changes
Awesome 👍

2021-07-27 10:12 UTC, HalcyonJAC requested changes

2021-07-27 10:12 UTC, HalcyonJAC commented on functions/shared/factories.js
> +      templateId = '5a4e7cbb-ab66-49a4-a8ad-7cbb399a8aa9'; // need a different reminder template
This template ID is the same as the above, but the code reads like it should be different. Is there a better way of doing this instead of inserting IDs into the code itself?

2021-07-27 10:12 UTC, HalcyonJAC commented on functions/shared/factories.js
> +        urlRequired: 'https://apply.judicialappointments.digital/sign-in',
Does this need to be environment specific?

2021-07-28 16:41 UTC, mbrookeswebdev commented on functions/shared/factories.js
> +      templateId = '5a4e7cbb-ab66-49a4-a8ad-7cbb399a8aa9'; // need a different reminder template
@HalcyonJAC we are in the process of setting up two different templates for a request and a reminder emails, so there will be two different IDs. Do you think we should set this up differently? I followed the IA/notifications pattern we already have following Warren's guidance.

2021-07-28 20:40 UTC, mbrookeswebdev commented on functions/shared/factories.js
> +        urlRequired: 'https://apply.judicialappointments.digital/sign-in',
I've made a change.

2021-07-28 20:51 UTC, HalcyonJAC commented on functions/shared/factories.js
> +      templateId = '5a4e7cbb-ab66-49a4-a8ad-7cbb399a8aa9'; // need a different reminder template
@mbrookeswebdev I guess as long as we don't forget to update the ID prior to deployment then that's fine! 😄 

If this is the agreed practise then no problem! I think personally, I would avoid storing IDs like this within the code itself and have a single place where IDs for templates are stored. I would potentially use something like a separate file which contains the templateName and the corresponding ID. Then you could use something like `getTemplateByName('characterCheckRequest')` which returns the relevant info on the template (ID and name) and keeps all that information in a single place and is reusable across the platform. Something to consider as a refactoring exercise in the future perhaps! 

Otherwise I tested it and it worked great 💥

2021-07-28 20:53 UTC, HalcyonJAC approved these changes

2021-08-05 15:06 UTC, tomlovesgithub approved these changes

2021-08-17 14:00 UTC, merged