Security/firestore rules testing
jac-uk/digital-platform pull request #582
Opened 2021-06-09 11:02 UTC by HalcyonJAC

Closes #257

2021-06-18 12:08 UTC, warrensearle commented
Hey @HalcyonJAC please see this PR #593. It includes a fix to the Timestamp issue we were experiencing. An resolves most of the broken tests

2021-06-18 16:53 UTC, tomlovesgithub approved these changes

2021-06-18 16:53 UTC, tomlovesgithub commented on .gitignore
> +data
is this a directory or file?
I just noticed data/firebase.json is still tracked

2021-06-21 08:18 UTC, HalcyonJAC commented on .gitignore
> +data
Hi,

That should be a directory, its interesting its still tracking the firebase.json file - because I didn't think I committed that.

However it might be worth keeping in, means it saves on firestore read quota when you run the emulator for the first time and it can be updated when the rules need updating for adding new properties etc.

2021-06-21 10:45 UTC, mbrookeswebdev reviewed
👍

2021-06-22 11:40 UTC, mbrookeswebdev approved these changes

2021-06-23 09:08 UTC, KateMJAC commented
@HalcyonJAC @warrensearle How are we going on this PR? does anything else need to be done or does the other #593 supersede it? 

Just want to see whther I can merge?

Thank you

2021-07-02 14:07 UTC, warrensearle requested changes
This looks good and it's great that we've made steps towards seeding the emulator database with content - that will be very useful moving forwards.

For our firestore security rules we have 149 passing tests however there are 7 failing. Can the failing tests be fixed as part of this ticket?

<img width="88" alt="image" src="https://user-images.githubusercontent.com/8524401/124286808-39929200-db47-11eb-8d6a-33669b232f75.png">

2021-07-18 15:14 UTC, londonprojects commented
@HalcyonJAC Can you give us an update here?

2021-07-21 11:34 UTC, HalcyonJAC commented
Will update by COP today @londonprojects. Thanks

2021-07-21 12:30 UTC, HalcyonJAC commented
Hi - this issue can no longer be merged as there are too many changes. The work needs to be re-done. Thanks

2021-08-18 09:31 UTC, closed without merging