#1078 - Create custom report
jac-uk/digital-platform pull request #631
Opened 2021-08-12 13:20 UTC by HalcyonJAC

See https://github.com/jac-uk/admin/pull/1469 for details

2021-08-12 15:20 UTC, warrensearle requested changes
Potential change... please see comment

2021-08-12 15:20 UTC, warrensearle commented on package.json
> +    "vuedraggable": "^2.24.3"
Not sure `vuedraggable` is needed here is it?

2021-08-20 14:22 UTC, warrensearle approved these changes
This all looks great. As discussed we need to iterate and either introduce caching or an intermediary store of the application ids for each stat.

2021-09-06 10:37 UTC, mbrookeswebdev approved these changes

2021-09-23 15:59 UTC, tomlovesgithub approved these changes

2021-10-01 14:42 UTC, merged