#1380 - User Roles Phase 1
jac-uk/digital-platform pull request #632
Opened 2021-08-12 15:03 UTC by HalcyonJAC

Please see https://github.com/jac-uk/admin/pull/1470 for further info

2021-08-12 15:34 UTC, warrensearle requested changes
Some questions / possible changes in the comments.

2021-08-12 15:34 UTC, warrensearle commented on functions/actions/userRoles.js
> +const userRoles = require('firebase-admin');
Could this be called `admin` instead of `userRoles`?
Also I think rather than requiring it here we could pass it into the module, similar to the way `db` is injected.

2021-08-12 15:34 UTC, warrensearle commented on functions/actions/userRoles.js
> +module.exports = (db) => {
`admin` could be passed in here

2021-08-12 15:34 UTC, warrensearle commented on functions/actions/userRoles.js
> +            isJacAdmin = true; // user has authenticated successfully with google or microsoft
We should restrict this to only `@judicialappointments.(digital|gov.uk)` email addresses, just to be sure.
I think currently anyone authenticated with google or microsoft would be allowed through...

2021-08-12 15:51 UTC, warrensearle commented on functions/actions/userRoles.js
> +            isJacAdmin = true; // user has authenticated successfully with google or microsoft
As discussed this will mean these users are included in the list of users the team can configure roles for.
Let's leave it as you have it in case the team want to see which users outside JAC have tried logging in to admin.
Plus in case the team want to assign a role to non-JAC email addresses.

2021-08-17 13:47 UTC, mbrookeswebdev approved these changes
👍

2021-08-25 08:14 UTC, warrensearle commented
As discussed @HalcyonJAC is going to amend so we are passing firebase (or auth) from `helpers` into the `userRoles` module

2021-11-10 09:30 UTC, warrensearle commented
Just the following to do then we're done
> As discussed @HalcyonJAC is going to amend so we are passing firebase (or auth) from `helpers` into the `userRoles` module

2021-12-09 13:55 UTC, warrensearle commented
@HalcyonJAC @JeremykJAC any update on this one?

2021-12-10 13:30 UTC, warrensearle commented
@HalcyonJAC I've made the code changes so will merge this work

2021-12-10 13:30 UTC, merged