Fix: Event Logger
jac-uk/digital-platform pull request #701
Opened 2022-04-13 17:07 UTC by warrensearle

Fixes a bug where cloud functions `onApplicationRecordUpdate` and `initialiseMissingApplicationRecords` were not behaving as expected.

The event logger module 'logEvent' was loading the `auth` service directly rather than it being injected. This meant our app instance was effectively being initialised twice!

Have updated all instances of `logEvent` so that `auth` is now passed in.

2022-04-14 08:42 UTC, tomlovesgithub approved these changes

2022-04-14 08:42 UTC, tomlovesgithub commented on nodeScripts/initialiseApplicationRecords.js
> +  return initialiseMissingApplicationRecords({
is it worth making another nodeScript for this? or maybe changing this one back to match the filename? (just seems potentially missable in the future)

2022-04-14 08:48 UTC, warrensearle commented on nodeScripts/initialiseApplicationRecords.js
> +  return initialiseMissingApplicationRecords({
Yes you're right @tomlovesgithub, I shall change the function back to match the script name. That said before running a node script you would usually check the content contains the params you want to be running. Plus the node scripts aren't deployed, they are just used by us devs to test out the code we've written... so we can be slightly less precise with them 😄  - e.g. feel free to add a script called `toms-script` and have it run whichever actions you like

2022-04-14 13:18 UTC, HalcyonJAC requested changes
Hi Warren, could you also modify the line 6 and 7 in the file `./functions/actions/applications/applications.js`. It will be imported by `createTestApplications.js` so need to pass `auth` into it as well.

Before:

```js
module.exports = (config, firebase, db) => {
  const { initialiseApplicationRecords } = require('../../actions/applicationRecords')(config, firebase, db);
```

After:

```js
module.exports = (config, firebase, db, auth) => {
  const { initialiseApplicationRecords } = require('../../actions/applicationRecords')(config, auth, firebase, db);
```

2022-04-26 09:18 UTC, HalcyonJAC approved these changes

2022-04-26 09:28 UTC, merged