#881 character check consent form submit template
jac-uk/digital-platform pull request #733
Opened 2022-06-16 10:12 UTC by HalcyonJAC

**Author checklist**

- [x] Include primary ticket number in title - e.g. "#123 New styling for widget" - and any additional tickets in description
- [x] Fill in the details below and delete as appropriate
- [x] Be proactive in getting your work approved 💪

---
## What's included?
1. Add  email template of character check consent form submit
2. Change firestore security rules to allow authenticated user to read their exercise.

## Who should test?
✅ Developers

## How to test?

Run node script `npm run nodeScript sendCharacterCheckRequests.js` and change the params. E.g.,

```
{
  items: ['xmnLGyEmaQd2w18BnCJP'],
  type: 'submit',
  exerciseMailbox: 'halcyon@judicialappointments.digital',
  exerciseManagerName: 'halcyon@judicialappointments.digital',
  dueDate: '13/06/2022',
}
```

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Additional context

## Related permissions
Have permissions been considered for this functionality?
- No permission changes required

---
PREVIEW:DEVELOP
_can be OFF, DEVELOP or STAGING_

2022-06-17 14:43 UTC, tomlovesgithub approved these changes
👍

2022-06-28 15:38 UTC, warrensearle requested changes
We need to keep `exercises` collection for JAC staff access only.

The `vacancies` collection exists to share data with candidates and the public so specific fields from `exercises` can be copied to `vacancies` if you need, providing they are public-facing.

2022-07-05 11:35 UTC, warrensearle requested changes
Almost there, just lets be super cautious about when emails are sent...

Right now email will only be sent when `application.characterChecks.status` changes to `'completed'`.

Lets introduce another field to ensure this only happens the first time the status changes to 'completed'.

2022-07-05 11:40 UTC, warrensearle commented on functions/actions/applications/onUpdate.js
> +        // send confirmation email if it hasn't been sent before
Just to be clear, with an object/map like the above we can track other emails too, e.g.:
```
emailLog: {
  applicationSubmitted: timestamp,
  characterCheckSubmitted: timestamp,
  ...
}
```

2022-07-05 13:04 UTC, HalcyonJAC commented on functions/actions/applications/onUpdate.js
> +        // send confirmation email if it hasn't been sent before
Thank you for your feedback. I've updated `emailLog.characterCheckSubmitted` once the character check consent form is submitted.

2022-07-08 09:29 UTC, warrensearle approved these changes
👍

2022-07-08 09:30 UTC, merged