#933 Application confirmation
jac-uk/digital-platform pull request #776
Opened 2022-10-20 13:10 UTC by HalcyonJAC

## What's included?
Send the application confirmation email to applicants after applications are submiited.

## Who should test?
✅ Developers

## How to test?
Run the command `npm run nodeScript sendApplicationConfirmation` in the terminal.

## Risk - how likely is this to impact other areas?
🟢 No risk - this is a self-contained piece of work

## Related permissions
- No permission changes required

---
PREVIEW:DEVELOP

2022-10-21 09:50 UTC, warrensearle requested changes
@HalcyonJAC this is good, just a few changes:

1. There's no need to retrieve the `application` document again as we already have it in the `dataAfter` object.
2. The `sendApplicationConfirmation` function should be amended to be solely for sending a single email as that's the functionality we are building & testing here. The current parameters indicate it could be used for sending multiple application emails but we are not building/testing for that functionality at this time.
3. Please include a flag, along the same lines as for the Character Consent email we discussed a few months ago, so that the email is only sent out once per candidate. e.g. If the application is changed from `draft` to `applied` to `draft` to `applied` then the candidate should receive one email not two. As things stand they would receive two emails.

Think that's it for now 😄

2022-10-21 15:14 UTC, HalcyonJAC commented
> @HalcyonJAC this is good, just a few changes:
> 
> 1. There's no need to retrieve the `application` document again as we already have it in the `dataAfter` object.
> 2. The `sendApplicationConfirmation` function should be amended to be solely for sending a single email as that's the functionality we are building & testing here. The current parameters indicate it could be used for sending multiple application emails but we are not building/testing for that functionality at this time.
> 3. Please include a flag, along the same lines as for the Character Consent email we discussed a few months ago, so that the email is only sent out once per candidate. e.g. If the application is changed from `draft` to `applied` to `draft` to `applied` then the candidate should receive one email not two. As things stand they would receive two emails.
> 
> Think that's it for now 😄

@warrensearle thank you for your suggestions. 😀

2022-10-28 09:28 UTC, warrensearle approved these changes
Great @HalcyonJAC thanks for making those changes ✅

2022-10-28 15:10 UTC, tomlovesgithub approved these changes

2022-11-02 09:21 UTC, merged