Create fullNameUC for applications sorting
jac-uk/digital-platform pull request #818
Opened 2023-01-06 12:00 UTC by HalcyonJAC

2023-01-06 13:19 UTC, warrensearle requested changes
Almost! 😄 
See comments

2023-01-06 13:19 UTC, warrensearle commented on functions/actions/applications/applications.js
> +    if (data.personalDetails.fullName) saveData['_sort.fullNameUC'] = data.personalDetails.fullName.toUpperCase();
This is updating the exercise document which is not what you want here. You'll need to update the `ref` passed in

2023-01-06 13:19 UTC, warrensearle commented on functions/actions/applications/onUpdate.js
> +      data['_sort.fullNameUC'] = dataAfter.personalDetails.fullName.toUpperCase();
This code could run if `dataBefore._sort` is missing however in this scenario we don't know whether we have `personalDetails.fullName` therefore you should check here, or in the `if` expression on line 99, that we have `personalDetails` and `personalDetails.fullName`

2023-01-06 13:19 UTC, warrensearle commented on functions/actions/applications/onUpdate.js
> +      data['_sort.fullNameUC'] = dataAfter.personalDetails.fullName.toUpperCase();
Actually modifying the `if` expression would be best as this update is only needed if we have `fullName`

2023-01-06 17:47 UTC, warrensearle requested changes
Almost just one teeny tiny change

2023-01-06 17:47 UTC, warrensearle commented on functions/actions/applications/applications.js
> +    if (data.personalDetails.fullName) {
Please change to `if (data.personalDetails && data.personalDetails.fullName)` just to be sure 😄

2023-01-09 09:08 UTC, HalcyonJAC commented on functions/actions/applications/applications.js
> +    if (data.personalDetails.fullName) {
Thank you for spotting it.

2023-01-09 09:21 UTC, warrensearle approved these changes
Great 👍

2023-01-09 11:05 UTC, merged