Generate statutory consultation report
jac-uk/digital-platform pull request #823
Opened 2023-01-12 09:25 UTC by HalcyonJAC

2023-01-16 09:38 UTC, warrensearle requested changes
Please see comments

2023-01-16 09:38 UTC, warrensearle commented on functions/actions/exercises/generateStatutoryConsultationReport.js
> +    );
Comment suggests you are retrieving only applications with the 'invited to selection day' status however your code is retrieving all applications. Please check and update comment or code accordingly.

2023-01-16 09:38 UTC, warrensearle commented on functions/shared/converters/lookup.js
> +    lookup[NOT_COMPLETE_PUPILLAGE_REASONS.OTHER] = 'Other - Please detail why you were exempt from undertaking pupillage by the Bar Standards Board';
Need to be careful here.
`NOT_COMPLETE_PUPILLAGE_REASONS.OTHER` has a value of "other" so this lookup will match for all occasions of 'other'.
I suggest removing the "Please detail why you..." text from the lookup. That feels like instruction text that should be on a form rather than part of a lookup.
Also check if there is already a constant for `'other'` and use that instead of `NOT_COMPLETE_PUPILLAGE_REASONS.OTHER`

2023-01-17 09:10 UTC, HalcyonJAC commented on functions/shared/converters/lookup.js
> +    lookup[NOT_COMPLETE_PUPILLAGE_REASONS.OTHER] = 'Other - Please detail why you were exempt from undertaking pupillage by the Bar Standards Board';
Thank you for spotting that. The key `other` already exists and I will remove `NOT_COMPLETE_PUPILLAGE_REASONS.OTHER` in `lookup.js`.

2023-01-17 11:28 UTC, HalcyonJAC commented on functions/actions/exercises/generateStatutoryConsultationReport.js
> +    );
Thank you. I have updated the query to retrieve the applications whose status is `invitedToSelectionDay`.

2023-01-17 11:34 UTC, warrensearle approved these changes
👍

2023-01-17 11:37 UTC, merged