#2252 User Management Comms & Search functionality
jac-uk/digital-platform pull request #987
Opened 2023-12-19 11:20 UTC by HalcyonJAC

2024-01-02 10:49 UTC, warrensearle requested changes
@HalcyonJAC I don't think we should be parsing the display name, trying to infer first name and last name and then storing the results in our database.

Let's just use display name as it comes through from Microsoft. This appears to be "lastName, firstName" so if we need sorting by lastName then we already have that. Likewise search can be based on email and display name, so we don't need to have parsed the display name for that either.

2024-01-02 10:49 UTC, warrensearle commented on functions/actions/users.js
> +const data = {};
Code needs indenting 🤓

2024-01-03 12:21 UTC, HalcyonJAC commented
@warrensearle Thanks for your feedback. I guess most admin users will log in to the platform with their Microsoft account and fewer with their Google account. The format of the display name from Google will be like "firstName lastName" which is different from Microsoft. I am not sure if we need to consider the display of users from Google.

2024-01-04 16:32 UTC, nickaddy commented
@HalcyonJAC In terms of testing, if I create a new account on production, the user should receive an email confirmation, right?

2024-01-05 14:36 UTC, HalcyonJAC commented
> @HalcyonJAC In terms of testing, if I create a new account on production, the user should receive an email confirmation, right?

@nickaddy Yes, the user should receive an invitation confirmation email if you create a new user invitation.

2024-01-08 10:49 UTC, warrensearle approved these changes
Thanks @dodosoya looks good to me

2024-01-08 11:47 UTC, merged